name: PHP

on: push

jobs:
  php:
    strategy:
      fail-fast: false
      matrix:
        version: [5.6, 7.4]
    runs-on: ubuntu-20.04
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - name: Repository checkout
        uses: actions/checkout@v3
      - name: Setup PHP ${{ matrix.version }}
        run: |
          sudo add-apt-repository ppa:ondrej/php
          sudo apt-get update
          sudo apt-get install -y php${{ matrix.version }}
      - name: Install quickbook
        run: |
          mkdir $HOME/bin
          wget -O $HOME/bin/quickbook https://github.com/boostorg/quickbook/releases/download/linux-binary/quickbook
          chmod a+x $HOME/bin/quickbook
          export PATH=$PATH:$HOME/bin
      - name: Install PHP dependencies
        run: |
          cd $GITHUB_WORKSPACE/common/code/test
          composer install --no-interaction --prefer-source
      - name: Run the tests
        run: |
          cd $GITHUB_WORKSPACE/common/code/test
          ./vendor/bin/tester -p php${{ matrix.version }} tests
          ./vendor/bin/tester -p php${{ matrix.version }}-cgi tests
      - name: Check that .php files are valid PHP
        run: |
          cd $GITHUB_WORKSPACE/
          find * -name 'vendor' -prune -o -name '*.php' -print | xargs grep -L 'CONTAINS_SYNTAX_ERROR' | xargs -n 1 php${{ matrix.version }} -l
      - name: Check .
        run: |
          cd $GITHUB_WORKSPACE/
          ./site-tools/update-doc-list.php
          ./site-tools/update-pages.php
          git status
